<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Dell-Namanmishar" ignored="0" name="restassuredtests" tests="23" failures="10" timestamp="2021-04-08T19:51:50 IST" time="10.278" errors="0">
  <testcase name="@BeforeClass getAllEmployees" time="3.879" classname="com.employee.testCases.TC005_Delete_Employee_Record">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at com.employee.testCases.TC005_Delete_Employee_Record.getAllEmployees(TC005_Delete_Employee_Record.java:28)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: The JSON input text should neither be null nor empty.
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:80)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 17 more
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass getAllEmployees -->
  <testcase name="@AfterClass tearDown" time="-1.617891704619E9" classname="com.employee.testCases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- @AfterClass tearDown -->
  <testcase name="checkContentType" time="0.0" classname="com.employee.testCases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkContentType -->
  <testcase name="checkResponseTime" time="0.0" classname="com.employee.testCases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkResponseTime -->
  <testcase name="checkStatusCode" time="0.0" classname="com.employee.testCases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkStatusCode -->
  <testcase name="checkstatusLine" time="0.0" classname="com.employee.testCases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkstatusLine -->
  <testcase name="checkResponseBody" time="0.032" classname="com.employee.testCases.TC001_Get_All_Employees"/>
  <testcase name="checkResponseTime" time="0.002" classname="com.employee.testCases.TC001_Get_All_Employees"/>
  <testcase name="checkStatusCode" time="0.007" classname="com.employee.testCases.TC001_Get_All_Employees">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at com.employee.testCases.TC001_Get_All_Employees.checkStatusCode(TC001_Get_All_Employees.java:45)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase name="checkstatusLine" time="0.002" classname="com.employee.testCases.TC001_Get_All_Employees">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]
at com.employee.testCases.TC001_Get_All_Employees.checkstatusLine(TC001_Get_All_Employees.java:67)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkstatusLine -->
  <testcase name="checkContentType" time="0.001" classname="com.employee.testCases.TC002_Get_Single_Employee_Data"/>
  <testcase name="checkResponseBody" time="0.002" classname="com.employee.testCases.TC002_Get_Single_Employee_Data"/>
  <testcase name="checkResponseTime" time="0.001" classname="com.employee.testCases.TC002_Get_Single_Employee_Data"/>
  <testcase name="checkStatusCode" time="0.002" classname="com.employee.testCases.TC002_Get_Single_Employee_Data"/>
  <testcase name="checkstatusLine" time="0.001" classname="com.employee.testCases.TC002_Get_Single_Employee_Data"/>
  <testcase name="checkContentType" time="0.005" classname="com.employee.testCases.TC004_Put_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [application/json] but found [text/html; charset=UTF-8]">
      <![CDATA[java.lang.AssertionError: expected [application/json] but found [text/html; charset=UTF-8]
at com.employee.testCases.TC004_Put_Employee_Record.checkContentType(TC004_Put_Employee_Record.java:94)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase name="checkResponseBody" time="0.002" classname="com.employee.testCases.TC004_Put_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employee.testCases.TC004_Put_Employee_Record.checkResponseBody(TC004_Put_Employee_Record.java:51)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseBody -->
  <testcase name="checkResponseTime" time="0.001" classname="com.employee.testCases.TC004_Put_Employee_Record"/>
  <testcase name="checkStatusCode" time="0.002" classname="com.employee.testCases.TC004_Put_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at com.employee.testCases.TC004_Put_Employee_Record.checkStatusCode(TC004_Put_Employee_Record.java:64)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase name="checkstatusLine" time="0.001" classname="com.employee.testCases.TC004_Put_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 405 Method Not Allowed]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 405 Method Not Allowed]
at com.employee.testCases.TC004_Put_Employee_Record.checkstatusLine(TC004_Put_Employee_Record.java:86)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkstatusLine -->
  <testcase name="checkContentType" time="0.001" classname="com.employee.testCases.TC003_Post_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [application/json] but found [text/html; charset=UTF-8]">
      <![CDATA[java.lang.AssertionError: expected [application/json] but found [text/html; charset=UTF-8]
at com.employee.testCases.TC003_Post_Employee_Record.checkContentType(TC003_Post_Employee_Record.java:94)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase name="checkResponseBody" time="0.001" classname="com.employee.testCases.TC003_Post_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employee.testCases.TC003_Post_Employee_Record.checkResponseBody(TC003_Post_Employee_Record.java:51)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseBody -->
  <testcase name="checkResponseTime" time="0.0" classname="com.employee.testCases.TC003_Post_Employee_Record"/>
  <testcase name="checkStatusCode" time="0.001" classname="com.employee.testCases.TC003_Post_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at com.employee.testCases.TC003_Post_Employee_Record.checkStatusCode(TC003_Post_Employee_Record.java:64)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase name="checkstatusLine" time="0.001" classname="com.employee.testCases.TC003_Post_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 405 Method Not Allowed]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 405 Method Not Allowed]
at com.employee.testCases.TC003_Post_Employee_Record.checkstatusLine(TC003_Post_Employee_Record.java:86)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkstatusLine -->
</testsuite> <!-- restassuredtests -->
